version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo_container
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongo:/data/db
    restart: always

volumes:
  mongo: